version: '3.9'

services:
  pythonapp:
    container_name: pythonapp
    image: pythonapp
    build: .
    command: >
      bash -c "flask db stamp head && 
               flask db migrate && 
               flask db upgrade &&
                flask run --host=0.0.0.0 --port=5000"
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:123@db:5432/app

    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: {}