"""new columns in the table User

Revision ID: bb3de1a402be
Revises: b77f9e8346ce
Create Date: 2022-04-09 12:27:36.459626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb3de1a402be'
down_revision = 'b77f9e8346ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chernovik')
    op.drop_table('cat')
    op.drop_table('aaa')
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    op.create_table('aaa',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('counter', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('cat',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cat', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('countt', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('chernovik',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('age', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
